#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define Login                                   101
#define APLICACION                              102
#define MYMENU                                  103
#define CUENTA                                  104
#define MODIFICARAPP                            105
#define ELIMINARAPP                             106
#define ELIMINARCUENTA                          107
#define MODIFICARCUENTA                         108
#define BTN_APLICACION                          401
#define BTN_ELIMINAR_APP                        402
#define BTN_ELIMINAR_CUENTA                     403
#define BTN_EDITAR_APP                          404
#define BTN_EDITAR_CUENTA                       405
#define LOGIN_BTN_CERRAR                        406
#define LOGIN_EDIT_CODIGO                       407
#define BTN_SALIR                               408
#define LOGIN_BTN_IMGRESAR                      410
#define BTN_CUENTA                              411
#define BTN_REGRESAR_MENU                       414
#define AP_BTN_MOD_NV                           415
#define CNT_BTN_MOD_NV                          416
#define HORARIO_DG                              420
#define AP_EDIT_C1                              1101
#define AP_EDIT_C2                              1102
#define AP_EDIT_C3                              1103
#define AP_EDIT_M1                              1104
#define AP_EDIT_E1                              1107
#define AP_BTN_C                                1108
#define AP_BTN_M                                1109
#define AP_BTN_E                                1110
#define CNT_EDIT_C1                             1201
#define CNT_EDIT_C2                             1202
#define CNT_EDIT_C3                             1203
#define CNT_EDIT_C4                             1204
#define CNT_EDIT_C5                             1205
#define CNT_EDIT_C6                             1206
#define CNT_EDIT_C7                             1207
#define CNT_EDIT_C8                             1208
#define CNT_EDIT_M1                             1216
#define CNT_EDIT_M2                             1217
#define CNT_EDIT_E1                             1220
#define CNT_EDIT_E2                             1221
#define CNT_BTN_C                               1222
#define CNT_BTN_M                               1223
#define CNT_BTN_E                               1224
#define G_EDIT_ESTADO                           1225
#define G_BTN_PRINTF_CMD_1                      1226
#define ID00                                    40000
#define ID10                                    40001
#define ID20                                    40002
#define ID30                                    40003
#define ID40                                    40004
#define ID01                                    40005
#define ID02                                    40006
#define ID03                                    40007
#define ID04                                    40008
#define ID05                                    40009
#define ID11                                    40010
#define ID21                                    40011
#define ID31                                    40012
#define ID41                                    40013
#define ID12                                    40014
#define ID13                                    40015
#define ID14                                    40016
#define ID15                                    40017
#define ID22                                    40018
#define ID32                                    40019
#define ID42                                    40020
#define ID23                                    40021
#define ID24                                    40022
#define ID25                                    40023
#define ID33                                    40024
#define ID43                                    40025
#define ID34                                    40026
#define ID35                                    40027
#define ID44                                    40028
#define ID45                                    40029
#define ESTADO1                                 40030
#define ESTADO2                                 40031
#define HORARIO_BTN                             40032
