#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define DLG_MAIN                                100
#define Login                                   101
#define APLICACION                              102
#define MYMENU                                  103
#define CUENTA                                  104
#define MODIFICARAPP                            105
#define ELIMINARAPP                             106
#define ELIMINARCUENTA                          107
#define MODIFICARCUENTA                         108
#define EDITAPLICACION                          109
#define EDITCUENTA                              110
#define AP_EDIT_C1                              1101
#define AP_EDIT_C2                              1102
#define AP_EDIT_C3                              1103
#define AP_EDIT_M1                              1104
#define AP_EDIT_M2                              1105
#define AP_EDIT_M3                              1106
#define AP_EDIT_E1                              1107
#define AP_BTN_C                                1108
#define AP_BTN_M                                1109
#define AP_BTN_E                                1110
#define CNT_EDIT_C1                             1201
#define CNT_EDIT_C2                             1202
#define CNT_EDIT_C3                             1203
#define CNT_EDIT_C4                             1204
#define CNT_EDIT_C5                             1205
#define CNT_EDIT_C6                             1206
#define CNT_EDIT_C7                             1207
#define CNT_EDIT_C8                             1208
#define CNT_EDIT_C9                             1209
#define CNT_EDIT_C10                            1210
#define CNT_EDIT_C11                            1211
#define CNT_EDIT_C12                            1212
#define CNT_EDIT_C13                            1213
#define CNT_EDIT_C14                            1214
#define CNT_EDIT_C15                            1215
#define CNT_EDIT_M1                             1216
#define CNT_EDIT_M2                             1217
#define CNT_EDIT_M3                             1218
#define CNT_EDIT_M4                             1219
#define CNT_EDIT_E1                             1220
#define CNT_EDIT_E2                             1221
#define CNT_BTN_C                               1222
#define CNT_BTN_M                               1223
#define CNT_BTN_E                               1224
#define G_EDIT_ESTADO                           1225
#define G_BTN_PRINTF_CMD_1                      1226
#define G_BTN_PRINTF_CMD_2                      1227
#define BTN_APLICACION                          4001
#define BTN_ELIMINAR_APP                        4002
#define BTN_ELIMINAR_CUENTA                     4003
#define BTN_EDITAR_APP                          4004
#define BTN_EDITAR_CUENTA                       4005
#define LOGIN_BTN_CERRAR                        4006
#define LOGIN_EDIT_CODIGO                       4007
#define BTN_SALIR                               4008
#define BTN_CREAR                               4009
#define LOGIN_BTN_IMGRESAR                      4010
#define BTN_CUENTA                              4011
#define BTN_REGRESAR_MENU                       4014
#define AP_BTN_MOD_NV                           4015
#define CNT_BTN_MOD_NV                          4016
#define CTN_POS_C                               4017
